version: '3.8'

services:
  app:
    build: .
    container_name: price_analysis_app
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    networks:
      - price_analysis_net

networks:
  price_analysis_net:
    driver: bridge